function Recipe() {
  let recipes = [
    {
      name: "Beef Tacos",
      image:
        "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      rating: 4.6,
      reviews: 278,
      prepTime: "15 min",
      cookTime: "20 min",
      servings: "4 people",
      ingredients: [
        "500g ground beef",
        "8 taco shells",
        "1 onion, diced",
        "2 tablespoons taco seasoning",
        "Shredded lettuce",
        "Diced tomatoes",
        "Shredded cheddar cheese",
        "Sour cream",
        "Salsa",
      ],
      instructions: [
        "Heat a large skillet over medium-high heat. Cook ground beef until browned.",
        "Add diced onion and cook until softened, about 5 minutes.",
        "Stir in taco seasoning and 1/2 cup water. Simmer for 10 minutes.",
        "Warm taco shells according to package directions.",
        "Fill each shell with seasoned beef.",
        "Top with lettuce, tomatoes, cheese, sour cream, and salsa.",
      ],
      nutrition: {
        calories: "420 kcal",
        protein: "26g",
        carbs: "32g",
        fat: "20g",
        fiber: "4g",
        sodium: "780mg",
      },
      tips: [
        "Drain excess fat from beef for healthier tacos",
        "Warm shells in oven for better texture",
        "Prepare all toppings before cooking beef",
        "Use ground turkey for a lighter option",
      ],
    },
    {
      name: "Classic Margherita Pizza",
      image:
        "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      rating: 4.8,
      reviews: 342,
      prepTime: "20 min",
      cookTime: "15 min",
      servings: "2 people",
      ingredients: [
        "1 pizza dough ball",
        "1/2 cup tomato sauce",
        "200g fresh mozzarella cheese",
        "Fresh basil leaves",
        "2 tbsp olive oil",
        "Salt and pepper",
      ],
      instructions: [
        "Preheat oven to 450°F (230°C).",
        "Roll out the pizza dough on a floured surface.",
        "Spread tomato sauce evenly over the dough.",
        "Top with slices of fresh mozzarella cheese.",
        "Bake for 10-15 minutes until crust is golden and cheese is bubbly.",
        "Garnish with fresh basil leaves and a drizzle of olive oil before serving.",
      ],
      nutrition: {
        calories: "300 kcal",
        protein: "12g",
        carbs: "35g",
        fat: "10g",
        fiber: "2g",
        sodium: "500mg",
      },
      tips: [
        "Use a pizza stone for a crispier crust",
        "Don't overload with sauce to avoid sogginess",
        "Add basil after baking to keep it fresh",
        "Use high-quality olive oil for finishing",
      ],
    },
    {
      name: "Grilled Lemon Herb Chicken",
      image:
        "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      rating: 4.7,
      reviews: 189,
      prepTime: "10 min",
      cookTime: "20 min",
      servings: "4 people",
      ingredients: [
        "4 chicken breasts",
        "2 lemons, juiced and zested",
        "3 tbsp olive oil",
        "2 cloves garlic, minced",
        "1 tbsp dried oregano",
        "Salt and pepper",
        "Fresh parsley",
      ],
      instructions: [
        "In a bowl, whisk together lemon juice, zest, olive oil, garlic, oregano, salt, and pepper.",
        "Marinate chicken breasts in the mixture for at least 30 minutes.",
        "Preheat grill to medium-high heat.",
        "Grill chicken for 6-8 minutes per side, or until cooked through.",
        "Garnish with fresh parsley and lemon slices.",
      ],
      nutrition: {
        calories: "250 kcal",
        protein: "30g",
        carbs: "2g",
        fat: "12g",
        fiber: "0g",
        sodium: "300mg",
      },
      tips: [
        "Marinate longer for deeper flavor",
        "Let chicken rest for 5 minutes after grilling",
        "Use a meat thermometer to ensure doneness",
        "Serve with grilled vegetables",
      ],
    },
    {
      name: "Vegetarian Stir-Fry",
      image:
        "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      rating: 4.5,
      reviews: 156,
      prepTime: "15 min",
      cookTime: "10 min",
      servings: "3 people",
      ingredients: [
        "1 block firm tofu, cubed",
        "2 cups broccoli florets",
        "1 red bell pepper, sliced",
        "1 carrot, sliced",
        "2 tbsp soy sauce",
        "1 tbsp sesame oil",
        "1 tsp ginger, minced",
        "2 cloves garlic, minced",
        "Cooked rice for serving",
      ],
      instructions: [
        "Press tofu to remove excess water, then cube.",
        "Heat sesame oil in a wok or large pan over high heat.",
        "Add tofu and stir-fry until golden. Remove from pan.",
        "Add garlic and ginger, cook for 30 seconds.",
        "Add vegetables and stir-fry for 5-7 minutes until tender-crisp.",
        "Return tofu to pan, add soy sauce, and toss to combine. Serve over rice.",
      ],
      nutrition: {
        calories: "350 kcal",
        protein: "15g",
        carbs: "45g",
        fat: "14g",
        fiber: "6g",
        sodium: "900mg",
      },
      tips: [
        "Cut veggies to uniform size for even cooking",
        "Don't overcrowd the pan",
        "Use high heat for a smoky flavor",
        "Add cashews for extra crunch",
      ],
    },
    {
      name: "Chocolate Chip Cookies",
      image:
        "https://images.unsplash.com/photo-1499636138143-bd630f5cf386?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80",
      rating: 4.9,
      reviews: 512,
      prepTime: "15 min",
      cookTime: "12 min",
      servings: "24 cookies",
      ingredients: [
        "2 1/4 cups all-purpose flour",
        "1 tsp baking soda",
        "1 cup butter, softened",
        "3/4 cup sugar",
        "3/4 cup brown sugar",
        "1 tsp vanilla extract",
        "2 large eggs",
        "2 cups chocolate chips",
      ],
      instructions: [
        "Preheat oven to 375°F (190°C).",
        "Combine flour and baking soda in a small bowl.",
        "Beat butter, sugar, brown sugar, and vanilla in large mixer bowl until creamy.",
        "Add eggs, one at a time, beating well after each addition.",
        "Gradually beat in flour mixture. Stir in chocolate chips.",
        "Drop by rounded tablespoon onto ungreased baking sheets.",
        "Bake for 9 to 11 minutes or until golden brown. Cool on wire racks.",
      ],
      nutrition: {
        calories: "180 kcal",
        protein: "2g",
        carbs: "22g",
        fat: "9g",
        fiber: "1g",
        sodium: "110mg",
      },
      tips: [
        "Use room temperature ingredients",
        "Chill dough for 1 hour for thicker cookies",
        "Don't overbake; they continue cooking on the sheet",
        "Use sea salt on top for flavor contrast",
      ],
    },
  ];
  return recipes;
}

function randomRecipe() {
  const recipes = Recipe();
  const randomIndex = Math.floor(Math.random() * recipes.length);
  console.log(recipes[randomIndex]);
  return randomIndex;
}
